#ifndef ENDPOINT_UTILS_H
#define ENDPOINT_UTILS_H

#include <StdAfx.h>

#define REFTIMES_PER_SEC       10000000
#define REFTIMES_PER_MILLISEC  10000

const UINT32 WAVE_HEAD_LEN     = 44;
const UINT32 WAVE_HEAD_EXT_LEN = 80;

#endif // !ENDPOINT_UTILS_H

